#OPENAI_API_KEY = "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"
[connections.snowpark]
#type="snowpark"
user = "learnatozaboutdata03"
password = "Learnatozaboutdata03@143#"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
# Find your account info here:
# https://docs.snowflake.com/en/user-guide/admin-account-identifier
account = "ie66159.ca-central-1.aws"
#https://mogphcp-uo47058.snowflakecomputing.com
#https://ie66159.ca-central-1.aws.snowflakecomputing.com